# based on https://github.com/PySlurm/pyslurm/blob/master/.travis.yml
sudo: required
language: julia
env:
  - SLURM=19.05.0

jobs:
  include:
    - stage: "Test"
      services:
        - docker
      before_install:
        - docker pull giovtorres/docker-centos7-slurm:$SLURM
        - docker run -d -it -h ernie -v $TRAVIS_BUILD_DIR:/SlurmTools -v $TRAVIS_HOME/julia:/julia --name slurm-$SLURM giovtorres/docker-centos7-slurm:$SLURM
      install: true
      before_script:
        - docker exec slurm-$SLURM /julia/bin/julia --project=/SlurmTools -e 'using Pkg; Pkg.build(verbose=true)'
      script:
        - docker exec slurm-$SLURM /julia/bin/julia --project=/SlurmTools -e 'using Pkg; Pkg.test()'

    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip